### ISSUE TITLE
Create an <ol> ordered list element with at least 3 items <li>, Items should contain different programming languages

### ISSUE THREAD

**Issue by r0nnie-20** [r0nnie-20/IcreatechsStudyHub#2]
After the <h1> and <p> element, create an <ol> ordered list containing 3 <li> items

**Comment by N3v1** [comment]
Hi r0nnie-20 👋,
i just saw your repo and noticed that you marked issue [**#2**](https://github.com/r0nnie-20/IcreatechsStudyHub/issues/2) as 'help-wanted'. I just sent a pull request, in which I created an ordered list with three programming languages ​​as stated in the description. If you want me to change something, please let me know. If the issue was for **lawrencecebrero** I'm very sorry.
